### ISSUE TITLE
ChangeLog

### ISSUE THREAD

**Issue by MaicolAntali** [MaicolAntali/BarattoManager#47]
##  🔄 Changelog
- Rimosse le classe Configurator e Viewer. _Rimpiazzate dalla classe User con l'aggiunta dell'attributo `isConfigurator`_
- SHA-512 delle password utenti. _Sicurezza_
- `AppConfigurator` non utilizza più una inner clan per essere singleton. _Classe utilizzata solo per lettura di dati non serve essere thread-safe_
- Nuova classe `MessageDialogDisplay` per gestire i JOptionPane

## 📑 Docs
Documentazione di parti molto complesse del progetto.

#### ♻️  MVC: ActionListener Annotation
- `ActionListenerFor` --> Annotazione da utilizzare **solo** sopra dei metodi. Questa annotazione richiede un parametro: `sourceField` che rappresenta il Field _(private o private final)_ della classe dove verrà aggiunta l'actionListener runtime.
-  `ActionListenerInstaller` --> Classe responsabile di trovare i tutti i metodi di una classe con l'annotazione `ActionListenerFor`, questo viene fatto attraverso l'analisi di classe, e successivamente invoca il metodo `addActionListener` sul filed dichiarato nell'annotazione attraverso un `InvocationHandler` e un `Proxy.newProxyInstance(...)`. 
- `ActionListenerLinked` --> Annotazione da utilizzare sopra i campi in moda da "marcare" quell campo 

![MVC-Annotations](https://user-images.githubusercontent.com/79454487/182326466-0d112d31-2594-45f8-9cd1-c4b78fa8ca6f.jpg)

**Comment by hali-d** [comment]
## Package Services

### Article, Category, Meet, Trade, User
- Le classi Deamon sono classi di controllo, ovvero la classe `MeetDeamon` controlla i meet e li aggiorna quando necessario, la classe `TradeDemon` controlla la validità degli scambi
- `*ManagerFactory` sono classi che costruiscono (new *Manager()) i Manager e ne permettono l'utilizzo (getManager())
- `*UpdateDataEvent` sono classi che gestiscono gli eventi tramite l'implementazione dell'interfaccia `UpdateDataHandler`, implementando i metodi di questa.
- `*UpdateDataEventFactory` sono classi che costruiscono (new *DataEventFactory()) e gestiscono (getEventHandler()) gli eventi di cui si ha bisogno

### Event
- L'interfaccia `UpdateDataHandler` è un'interfaccia generica che gestisce gli eventi. Contiene due metodi, l'**addListener** che aggiunge un listener all'evento, e il **fireListener** che avvia l'evento di ciascun listener
- L'interfaccia `UpdateDataListener` è stata creata per gestire il cambiamento dei dati. Contiene il metodo **update**, non implementato, che viene invocato ogni volta che vi sono dei cambiamenti di dati di una mappa (ConcurrentHashMap).

### History
- La classe `History` è definita come **Record**, questo per salvare dati immutabili di un oggetto, nel nostro caso i dati relativi alla creazione degli articoli e alla gestione degli scambi

### Json
- La classe `JsonHandler` è una classe che gestisce i file JSON. Contiene un metodo per la lettura del file (readJson) che restituisce una mappa  (ConcurrentHashMap) con valori, e un metodo override (update) che permettere di salvare i dati aggiornati. Quest'ultimo metodo permetto tale funzionalià grazie all'implementazione dell'interfaccia `UpdateDataListener`

### Store
- Classe `Store` è stata creata per la gestione dell'utente che ha fatto l'accesso. Contiene due metodi, tramite il metodo di **setLoggedUser()** si ha la possibilità di memorizzare l'utente che ha fatto il login e tramite il metodo **getLoggedUser()** si ha la possibilità di gestirlo

## Package UI

### Annotation 
- Le Annotation sono di tre tipologie ma hanno la stessa logica spiegata qua https://github.com/MaicolAntali/BarattoManager/issues/47#issue-1319687979

### Base 
- L'interfaccia `BaseController` è un'interfaccia comune per tutti controller, cotituita da due metodi **getBaseModel()** che restituisce un BaseModel e **getBaseView()** che restituisce una BaseView. Questi metodi permettono l'utilizzo del model e della view e vengono definiti in questa interfaccia in quanto comuni a tutti i controller
- L'interfeccia `BaseModel`  è un'interfaccia generica dedicata all'acceso dati, vuota in quanto i model contengono dati diversi tra loro. In acluni casi questa interfaccia non viene utilizzata in quanto non vi è necessita di utilizzo dati
- L'interfaccia `BaseView` è un'interfaccia generica che va a rappresentare l'interfaccia utente, contiene un unico metodo comune a tutte le view **getMainPanel()** che restituisce il Panel dell'interfaccia utente

### MVC
- Tutti i Controller, Model, View implementano le interfaccie Base e di conseguenza anche i metodi di queste

#### Homepage
- `*HompageController` hanno tutti simile struttura, presentano un contruttore che inizializza la `*HompageView` ed costituisce l'invocazione del metodo **proccessAnnotation** della classe ActionListenerInstaller per l'utilizzo delle Annotation. Oltre a questo presentano metodi **clickOn*** la cui implementazione consiste nella registrazione e visualizzazione della MVC di ciascun bottone (Questi metodi sono presenti in tutti controller nel progetto ad eccezione del mainFrame)
- `*HompageView` hanno struttura simile, differenziano solo di titolo e bottoni

#### Configurator, Viewer
- Le View dei bottoni del Configurator e del View hanno un metodo in comune aggiuntivo per impostare l'albero **setTreePanel**
- Le classi `*Controller` dei bottoni del Confgurator e del Viewer hanno simile struttura, il costruttore oltre ad inizializzare la view ed installare l'annotation, crea l'albero del corrispettivo bottone e lo imposta nella view tramite l'invocazione del metodo **setTreePanel** presente nella classe `*View`. Le uniche eccezioni sono le classi `ViewerStoreArticleController`, `ViewerYourArticleController`, `ViewerTradesController` che oltre a tutto ciò il costruttore contiene anche la creazione del menu a tendina del corrispondente controller e lo imposta nella view tramite l'invocazione del metodo **setMenuPanel** presente nella classe `*View`

#### Dialogs
- I dialog vanno a rappresentare le finestre di dialogo in cui si inseriscono informazioni, nel nostro caso vengono utilizzati per la creazione di nuovi oggeti e la selezione di questi. I `*Controller` hanno la stessa struttura di base, la particolarità sono i `*Model`, in quanto vi è necessita di accesso ai dati, perciò ciascun model è costituto da dati corrispondenti ai campi del proprio dialog e presenta metodi di **set** per la modifica/aggiornamento di questi dati

#### MainFrame
- La classe `MainFrameController`, rappresenta il controller del frame iniziale dell'app, costituita da un costruttore che va ad inizializzare il MainFrameModel e la MainFrameView e a settare la versione dell'app 
- Questa classe inoltre implementa le interfaccie `RegisterControllerListener` e `ShowControllerListener` per andare ad implementare i metodi **register()**, per la registrazione dei controller invocando metodi del model (addNewController), ed **show()** per la visualizzazione dei controller nel mainFrame invocando metodi della view (updateContentPanel)
- La classe `MainFrameModel`, rappresenta il model, si occupa quindi dell'accesso ai dati. Costituita da due metodi:  **addNewController**, metodo che si occupa di aggiungere un controller alla mappa di controller (controllerHashMap), dopo la verifica di precedente esistenza; **getControllerByName** metodo che restituisce un controller, dopo averlo ricercato per nome nella mappa dei controller
- La classe `MainFrameView`, rappresenta la view, costituita dal metodo **updateContentPanel** che consiste nel caricamento del panel del controller nella view del mainFrame, dopo la verifica di precedente esistenza. Questo metodo viene invocato dalla classe `MainFrameController` nel metodo **show**

##### events
- `*ControllerHandlerFactory` sono classi che hanno scopo di creazione del *ControllerHendlear che andra a gestire gli eventi
- `*ControllerHeandler` sono classi che gestisce gli eventi. Contengono due metodi, l'**addListener** che aggiunge un listener all'evento, e il **fireListener** che avvia l'evento di ciascun listener
- `*ControllerListener` sono interfaccie generiche create per registrare/mostrare i Controller creati, questo tramite i metodi  **void register** e **void show** che verranno implementati nella classe `MainframeController`

### Utils

#### MessageDialog
- E' una classe di utilità che rappresenta un dialog standard che forisce informazioni (nel nostro caso gli errori), costituita da attributi che verranno impostati quando invocata tramite i metodi **set** e dal metodo **show** che permettera la visualizzazione di questo

#### OptionDialog
- A differenza di quello precedentemente, questa classe rappresenta un dialog standard di conferma, ha la stessa struttura di messageDialog ed in aggiunta un attributo detto **optionType** che va a rappresentare i bottoni di conferma e cancellazione

## Package Utils

### Parser
- `DateParser` utilizzata per associare una stringa ad un giorno della settimana della classe **enum** DaysOfWeek di java
- `StringParser` utilizzata per convertire una stringa in un intero
- `TimeParser` utilizzata per convertire una stringa o un intero in tempo, ovvero in minuti

### SHA256
- `SHA256` è una classe utilizzata per la codifica delle password. presenta due metodi
-- **hash(String str)**, utilizzato per codificare la stringa password in un array di bytes seguendo l'algoritmo SHA-256
-- **bytesToString(byte[] hash)**, utilizzato per la convertire un array di bytes in una stringa
