### ISSUE TITLE
Bug: Field in sub-category

### ISSUE THREAD

**Issue by Shubho10** [MaicolAntali/BarattoManager#5]
https://github.com/MaicolAntali/BarattoManager/blob/60a343217172ec929bf72853829012fff969846d/src/com/barattoManager/ui/panels/ConfiguratorCategoryEditorUi.java#L19

Quando si crea un nuovo campo per la categoria radice, nelle sotto-sotto-categorie il campo non viene aggiunto.

un'altra cosa che vorrei sottolineare è che quando clicco su un campo e cerco di creare un nuovo campo, l'applicazione non fa niente, non è un errore ma volevo solo sottolineare la cosa per confermare che tu sappia di questa cosa.

**Comment by MaicolAntali** [comment]
> un'altra cosa che vorrei sottolineare è che quando clicco su un campo e cerco di creare un nuovo campo, l'applicazione non fa niente, non è un errore ma volevo solo sottolineare la cosa per confermare che tu sappia di questa cosa.

Si è coretto
